# Generated by Django 3.0.6 on 2020-05-27 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bokmark',
            new_name='Bookmark',
        ),
    ]
